connect_debug_port u_ila_0/probe7 [get_nets [list trigger_dacs_pulse]]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property MARK_DEBUG true [get_nets {ps_gpin[15]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[12]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[11]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[10]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[9]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[8]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_ps2/ps1_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[0]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[1]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 5 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_dacs_pulse/wave_errors[0][0]} {u_dacs_pulse/wave_errors[0][1]} {u_dacs_pulse/wave_errors[0][2]} {u_dacs_pulse/wave_errors[0][3]} {u_dacs_pulse/wave_errors[0][4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ps_gpout[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {dacs_pulse_axis_tdatas[0][0]} {dacs_pulse_axis_tdatas[0][1]} {dacs_pulse_axis_tdatas[0][2]} {dacs_pulse_axis_tdatas[0][3]} {dacs_pulse_axis_tdatas[0][4]} {dacs_pulse_axis_tdatas[0][5]} {dacs_pulse_axis_tdatas[0][6]} {dacs_pulse_axis_tdatas[0][7]} {dacs_pulse_axis_tdatas[0][8]} {dacs_pulse_axis_tdatas[0][9]} {dacs_pulse_axis_tdatas[0][10]} {dacs_pulse_axis_tdatas[0][11]} {dacs_pulse_axis_tdatas[0][12]} {dacs_pulse_axis_tdatas[0][13]} {dacs_pulse_axis_tdatas[0][14]} {dacs_pulse_axis_tdatas[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {dacs_pulse_axis_treadys[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {dacs_pulse_axis_tvalids[0]} {dacs_pulse_axis_tvalids[1]} {dacs_pulse_axis_tvalids[2]} {dacs_pulse_axis_tvalids[3]} {dacs_pulse_axis_tvalids[4]} {dacs_pulse_axis_tvalids[5]} {dacs_pulse_axis_tvalids[6]} {dacs_pulse_axis_tvalids[7]} {dacs_pulse_axis_tvalids[8]} {dacs_pulse_axis_tvalids[9]} {dacs_pulse_axis_tvalids[10]} {dacs_pulse_axis_tvalids[11]} {dacs_pulse_axis_tvalids[12]} {dacs_pulse_axis_tvalids[13]} {dacs_pulse_axis_tvalids[14]} {dacs_pulse_axis_tvalids[15]} {dacs_pulse_axis_tvalids[16]} {dacs_pulse_axis_tvalids[17]} {dacs_pulse_axis_tvalids[18]} {dacs_pulse_axis_tvalids[19]} {dacs_pulse_axis_tvalids[20]} {dacs_pulse_axis_tvalids[21]} {dacs_pulse_axis_tvalids[22]} {dacs_pulse_axis_tvalids[23]} {dacs_pulse_axis_tvalids[24]} {dacs_pulse_axis_tvalids[25]} {dacs_pulse_axis_tvalids[26]} {dacs_pulse_axis_tvalids[27]} {dacs_pulse_axis_tvalids[28]} {dacs_pulse_axis_tvalids[29]} {dacs_pulse_axis_tvalids[30]} {dacs_pulse_axis_tvalids[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 5 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ps_gpin[8]} {ps_gpin[9]} {ps_gpin[10]} {ps_gpin[11]} {ps_gpin[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list misc_trigger]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list p2p_busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list dacs_pulse_busy]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list ps_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 31 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {dacs_pulse_axis_treadys[1]} {dacs_pulse_axis_treadys[2]} {dacs_pulse_axis_treadys[3]} {dacs_pulse_axis_treadys[4]} {dacs_pulse_axis_treadys[5]} {dacs_pulse_axis_treadys[6]} {dacs_pulse_axis_treadys[7]} {dacs_pulse_axis_treadys[8]} {dacs_pulse_axis_treadys[9]} {dacs_pulse_axis_treadys[10]} {dacs_pulse_axis_treadys[11]} {dacs_pulse_axis_treadys[12]} {dacs_pulse_axis_treadys[13]} {dacs_pulse_axis_treadys[14]} {dacs_pulse_axis_treadys[15]} {dacs_pulse_axis_treadys[16]} {dacs_pulse_axis_treadys[17]} {dacs_pulse_axis_treadys[18]} {dacs_pulse_axis_treadys[19]} {dacs_pulse_axis_treadys[20]} {dacs_pulse_axis_treadys[21]} {dacs_pulse_axis_treadys[22]} {dacs_pulse_axis_treadys[23]} {dacs_pulse_axis_treadys[24]} {dacs_pulse_axis_treadys[25]} {dacs_pulse_axis_treadys[26]} {dacs_pulse_axis_treadys[27]} {dacs_pulse_axis_treadys[28]} {dacs_pulse_axis_treadys[29]} {dacs_pulse_axis_treadys[30]} {dacs_pulse_axis_treadys[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {ps_gpin[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets ps_clk0]
