connect_debug_port u_ila_0/probe7 [get_nets [list trigger_dacs_pulse]]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property MARK_DEBUG true [get_nets {ps_gpin[15]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[12]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[11]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[10]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[9]}]
set_property MARK_DEBUG true [get_nets {ps_gpin[8]}]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_dacs_pulse/wave_errors[0][0]} {u_dacs_pulse/wave_errors[0][1]} {u_dacs_pulse/wave_errors[0][2]} {u_dacs_pulse/wave_errors[0][3]} {u_dacs_pulse/wave_errors[0][4]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {ps_gpin[8]} {ps_gpin[9]} {ps_gpin[10]} {ps_gpin[11]} {ps_gpin[12]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list p2p_busy]]
connect_debug_port u_ila_1/clk [get_nets [list ps_clk0]]
connect_debug_port u_ila_1/probe0 [get_nets [list {dacs_pulse_axis_treadys[1]} {dacs_pulse_axis_treadys[2]} {dacs_pulse_axis_treadys[3]} {dacs_pulse_axis_treadys[4]} {dacs_pulse_axis_treadys[5]} {dacs_pulse_axis_treadys[6]} {dacs_pulse_axis_treadys[7]} {dacs_pulse_axis_treadys[8]} {dacs_pulse_axis_treadys[9]} {dacs_pulse_axis_treadys[10]} {dacs_pulse_axis_treadys[11]} {dacs_pulse_axis_treadys[12]} {dacs_pulse_axis_treadys[13]} {dacs_pulse_axis_treadys[14]} {dacs_pulse_axis_treadys[15]} {dacs_pulse_axis_treadys[16]} {dacs_pulse_axis_treadys[17]} {dacs_pulse_axis_treadys[18]} {dacs_pulse_axis_treadys[19]} {dacs_pulse_axis_treadys[20]} {dacs_pulse_axis_treadys[21]} {dacs_pulse_axis_treadys[22]} {dacs_pulse_axis_treadys[23]} {dacs_pulse_axis_treadys[24]} {dacs_pulse_axis_treadys[25]} {dacs_pulse_axis_treadys[26]} {dacs_pulse_axis_treadys[27]} {dacs_pulse_axis_treadys[28]} {dacs_pulse_axis_treadys[29]} {dacs_pulse_axis_treadys[30]} {dacs_pulse_axis_treadys[31]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {ps_gpin[15]}]]
connect_debug_port dbg_hub/clk [get_nets ps_clk0]

