connect_debug_port u_ila_0/probe0 [get_nets [list {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[0]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[1]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[2]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[3]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[4]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[5]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[6]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[7]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[8]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[9]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[10]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[11]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[12]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[13]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[14]} {u_pulse2pmod0/u_axi_fifo/s_axis_tdata[15]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[0]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[1]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[2]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[3]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[4]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[5]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[6]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[7]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[8]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[9]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[10]} {u_pulse2pmod0/u_dac_pulse/m_axis_tdata[11]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_pulse2pmod0/fifo_axis_tdata[0]} {u_pulse2pmod0/fifo_axis_tdata[1]} {u_pulse2pmod0/fifo_axis_tdata[2]} {u_pulse2pmod0/fifo_axis_tdata[3]} {u_pulse2pmod0/fifo_axis_tdata[4]} {u_pulse2pmod0/fifo_axis_tdata[5]} {u_pulse2pmod0/fifo_axis_tdata[6]} {u_pulse2pmod0/fifo_axis_tdata[7]} {u_pulse2pmod0/fifo_axis_tdata[8]} {u_pulse2pmod0/fifo_axis_tdata[9]} {u_pulse2pmod0/fifo_axis_tdata[10]} {u_pulse2pmod0/fifo_axis_tdata[11]} {u_pulse2pmod0/fifo_axis_tdata[12]} {u_pulse2pmod0/fifo_axis_tdata[13]} {u_pulse2pmod0/fifo_axis_tdata[14]} {u_pulse2pmod0/fifo_axis_tdata[15]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list u_pulse2pmod0/u_axi_fifo/almost_empty]]
connect_debug_port u_ila_0/probe4 [get_nets [list u_pulse2pmod0/u_axi_fifo/almost_full]]
connect_debug_port u_ila_0/probe5 [get_nets [list u_pulse2pmod0/fifo_axis_tvalid]]
connect_debug_port u_ila_0/probe6 [get_nets [list u_pulse2pmod0/u_dac_pulse/m_axis_tvalid]]
connect_debug_port u_ila_0/probe7 [get_nets [list u_pulse2pmod0/u_axi_fifo/s_axis_tlast]]
connect_debug_port u_ila_0/probe8 [get_nets [list u_pulse2pmod0/u_axi_fifo/s_axis_tvalid]]

set_property MARK_DEBUG true [get_nets fifo_axis_tlast]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][6]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][13]}]
set_property MARK_DEBUG true [get_nets fifo_axis_tready]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][7]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][11]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][14]}]
set_property MARK_DEBUG true [get_nets misc_trigger]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][3]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][5]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][15]}]
set_property MARK_DEBUG true [get_nets fifo_almost_empty]
set_property MARK_DEBUG true [get_nets fifo_axis_tvalid]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][0]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][2]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][4]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][8]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][9]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][10]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][12]}]

set_property MARK_DEBUG false [get_nets {ps_leds[2]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[9]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets {fifo_axis_tdata[14]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_ps2/ps1_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {fifo_axis_tdata[0]} {fifo_axis_tdata[1]} {fifo_axis_tdata[2]} {fifo_axis_tdata[3]} {fifo_axis_tdata[4]} {fifo_axis_tdata[5]} {fifo_axis_tdata[6]} {fifo_axis_tdata[7]} {fifo_axis_tdata[8]} {fifo_axis_tdata[9]} {fifo_axis_tdata[10]} {fifo_axis_tdata[11]} {fifo_axis_tdata[12]} {fifo_axis_tdata[13]} {fifo_axis_tdata[14]} {fifo_axis_tdata[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {dacs_pulse_axis_tdatas[0][0]} {dacs_pulse_axis_tdatas[0][1]} {dacs_pulse_axis_tdatas[0][2]} {dacs_pulse_axis_tdatas[0][3]} {dacs_pulse_axis_tdatas[0][4]} {dacs_pulse_axis_tdatas[0][5]} {dacs_pulse_axis_tdatas[0][6]} {dacs_pulse_axis_tdatas[0][7]} {dacs_pulse_axis_tdatas[0][8]} {dacs_pulse_axis_tdatas[0][9]} {dacs_pulse_axis_tdatas[0][10]} {dacs_pulse_axis_tdatas[0][11]} {dacs_pulse_axis_tdatas[0][12]} {dacs_pulse_axis_tdatas[0][13]} {dacs_pulse_axis_tdatas[0][14]} {dacs_pulse_axis_tdatas[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list fifo_almost_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list fifo_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list fifo_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list fifo_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list misc_trigger]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
