onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_qlaser_top/clk
add wave -noupdate /tb_qlaser_top/p_reset
add wave -noupdate /tb_qlaser_top/p_dc0_sclk
add wave -noupdate /tb_qlaser_top/p_dc0_mosi
add wave -noupdate /tb_qlaser_top/p_dc0_cs_n
add wave -noupdate /tb_qlaser_top/p_dc1_sclk
add wave -noupdate /tb_qlaser_top/p_dc1_mosi
add wave -noupdate /tb_qlaser_top/p_dc1_cs_n
add wave -noupdate /tb_qlaser_top/p_dc2_sclk
add wave -noupdate /tb_qlaser_top/p_dc2_mosi
add wave -noupdate /tb_qlaser_top/p_dc2_cs_n
add wave -noupdate /tb_qlaser_top/p_dc3_sclk
add wave -noupdate /tb_qlaser_top/p_dc3_mosi
add wave -noupdate /tb_qlaser_top/p_dc3_cs_n
add wave -noupdate /tb_qlaser_top/p_btn_e
add wave -noupdate /tb_qlaser_top/p_btn_s
add wave -noupdate /tb_qlaser_top/p_btn_n
add wave -noupdate /tb_qlaser_top/p_btn_w
add wave -noupdate /tb_qlaser_top/p_btn_c
add wave -noupdate /tb_qlaser_top/p_leds
add wave -noupdate /tb_qlaser_top/p_debug_out
add wave -noupdate /tb_qlaser_top/sim_done
add wave -noupdate /tb_qlaser_top/CLK_FREQ_MHZ
add wave -noupdate /tb_qlaser_top/CLK_PER
add wave -noupdate /tb_qlaser_top/ADR_RAM_PULSE
add wave -noupdate /tb_qlaser_top/ADR_RAM_WAVE
add wave -noupdate /tb_qlaser_top/vout0
add wave -noupdate -divider qlaser_top
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_reset
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc0_sclk
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc0_mosi
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc0_cs_n
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc1_sclk
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc1_mosi
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc1_cs_n
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc2_sclk
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc2_mosi
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc2_cs_n
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc3_sclk
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc3_mosi
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_dc3_cs_n
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_btn_e
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_btn_s
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_btn_n
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_btn_w
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_btn_c
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_leds
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p_debug_out
add wave -noupdate /tb_qlaser_top/u_qlaser_top/clk
add wave -noupdate /tb_qlaser_top/u_qlaser_top/reset
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cif_reset
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cpu_sels
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cpu_wr
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cpu_addr
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cpu_din
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cpu_debug
add wave -noupdate /tb_qlaser_top/u_qlaser_top/arr_cpu_dout
add wave -noupdate /tb_qlaser_top/u_qlaser_top/arr_cpu_dout_dv
add wave -noupdate /tb_qlaser_top/u_qlaser_top/misc_leds
add wave -noupdate /tb_qlaser_top/u_qlaser_top/misc_leds_en
add wave -noupdate /tb_qlaser_top/u_qlaser_top/misc_flash
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tick_msec
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tick_sec
add wave -noupdate /tb_qlaser_top/u_qlaser_top/misc_dbg_ctrl
add wave -noupdate /tb_qlaser_top/u_qlaser_top/misc_trigger
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_clk0
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_resetn0
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_leds
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_gpin
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_gpout
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_clk_cpu
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_cpu_addr
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_cpu_wdata
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_cpu_wr
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_cpu_rd
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cif_cpu_rdata
add wave -noupdate /tb_qlaser_top/u_qlaser_top/cif_cpu_rdata_dv
add wave -noupdate /tb_qlaser_top/u_qlaser_top/pulse
add wave -noupdate /tb_qlaser_top/u_qlaser_top/pulse_stretched
add wave -noupdate /tb_qlaser_top/u_qlaser_top/trigger_dacs_pulse
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_enable_dacs_pulse
add wave -noupdate /tb_qlaser_top/u_qlaser_top/any_dacs_busy
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_dc_busy
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_ready
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_busy
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_error
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_error_latched
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_axis_treadys
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_axis_tdatas
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_axis_tvalids
add wave -noupdate /tb_qlaser_top/u_qlaser_top/dacs_pulse_axis_tlasts
add wave -noupdate /tb_qlaser_top/u_qlaser_top/jesd_syncs
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p2p_busy
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p2p_spi_sclk
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p2p_spi_mosi
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p2p_spi_cs_n
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p2pmodBusyD4
add wave -noupdate /tb_qlaser_top/u_qlaser_top/p2p_active
add wave -noupdate /tb_qlaser_top/u_qlaser_top/gpio_btns
add wave -noupdate /tb_qlaser_top/u_qlaser_top/s_axis_tx_fmc0_tdata
add wave -noupdate /tb_qlaser_top/u_qlaser_top/s_axis_tx_fmc0_tready
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tx0_aresetn
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tx0_core_reset
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tx0_reset_done
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tx0_sof
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tx0_somf
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tx0_sync
add wave -noupdate /tb_qlaser_top/u_qlaser_top/tx0_sysref
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_jesd_tx0outclk
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_jesd_tx0n_out
add wave -noupdate /tb_qlaser_top/u_qlaser_top/ps_jesd_tx0p_out
add wave -noupdate /tb_qlaser_top/u_qlaser_top/SEL_DAC_DC
add wave -noupdate /tb_qlaser_top/u_qlaser_top/SEL_DAC_PULSE
add wave -noupdate /tb_qlaser_top/u_qlaser_top/SEL_MISC
add wave -noupdate /tb_qlaser_top/u_qlaser_top/SEL_SPARE
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 2} {1178950385 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 163
configure wave -valuecolwidth 200
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits fs
update
WaveRestoreZoom {0 fs} {3240305351 fs}
