####################################################################################
# Constraints from file : 'fifo_pmod_dbg.xdc'
####################################################################################

set_property MARK_DEBUG true [get_nets {dacs_dc_busy[0]}]
set_property MARK_DEBUG true [get_nets {dacs_dc_busy[2]}]
set_property MARK_DEBUG true [get_nets {dacs_dc_busy[3]}]
set_property MARK_DEBUG true [get_nets {ps_gpout[0]}]
set_property MARK_DEBUG true [get_nets {ps_gpout[1]}]
set_property MARK_DEBUG true [get_nets {ps_gpout[2]}]
set_property MARK_DEBUG true [get_nets dacs_pulse_busy]
set_property MARK_DEBUG true [get_nets {pulse_errors[0][0]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[0][1]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[0][2]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[0][3]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[0][4]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[1][0]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[1][1]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[1][2]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[1][3]}]
set_property MARK_DEBUG true [get_nets {pulse_errors[1][4]}]
set_property MARK_DEBUG true [get_nets reg_sequence_len]
set_property MARK_DEBUG true [get_nets trigger_dacs_pulse]



set_property MARK_DEBUG true [get_nets fifo_almost_empty0]
set_property MARK_DEBUG true [get_nets fifo_almost_empty1]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[8]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[10]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[13]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[0]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[1]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[2]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[3]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[8]}]
set_property MARK_DEBUG true [get_nets fifo_axis0_tvalid]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[0]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[5]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[7]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[11]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[7]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[11]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[12]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[15]}]
set_property MARK_DEBUG true [get_nets fifo_axis0_tlast]
set_property MARK_DEBUG true [get_nets fifo_axis1_tlast]
set_property MARK_DEBUG true [get_nets fifo_axis1_tvalid]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[1]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[3]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[4]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[6]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[9]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[10]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[13]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[14]}]
set_property MARK_DEBUG true [get_nets fifo_axis1_tready]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[2]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[6]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[9]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[12]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[14]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[15]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[4]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[5]}]
set_property MARK_DEBUG true [get_nets p2p0_busy]
set_property MARK_DEBUG true [get_nets p2p1_busy]




set_property MARK_DEBUG true [get_nets clk]

set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][0]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][3]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][6]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][13]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][6]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][9]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][11]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][12]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][4]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][2]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][7]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][12]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][14]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][4]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][5]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][15]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][5]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][8]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][11]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][15]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][8]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][10]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][9]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][10]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][0]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][2]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][3]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][7]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][13]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][14]}]


connect_debug_port u_ila_0/probe1 [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[0]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[1]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[2]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[3]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[4]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[5]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[6]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[7]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[8]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[9]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[10]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[11]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[12]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[13]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[14]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[15]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[16]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[17]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[18]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[19]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[20]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[21]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[22]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[23]}]]

connect_debug_port u_ila_0/probe0 [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[0]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[1]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[2]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[3]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[4]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[5]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[6]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[7]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[8]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[9]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[10]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[11]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[12]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[13]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[14]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[15]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[16]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[17]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[18]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[19]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[20]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[21]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[22]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]_i_9_0[23]}]]
# [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[0]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[1]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state[2]}]]


set_property MARK_DEBUG true [get_nets p_dc3_cs_n_OBUF]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/axis_tvalids[0]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/axis_tvalids[1]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/p_1_in}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/sm_state_reg_n_0_[0]}]
connect_debug_port u_ila_0/probe19 [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/p_1_in}]]


set_property MARK_DEBUG true [get_nets {cpu_addr[0]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[1]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[2]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[5]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[6]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[7]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[11]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[3]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[4]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[8]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[9]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[10]}]
set_property MARK_DEBUG true [get_nets {cpu_addr[12]}]

set_property MARK_DEBUG true [get_nets {u_cif/cpu_sels[0]}]
set_property MARK_DEBUG true [get_nets {u_cif/cpu_sels[1]}]
set_property MARK_DEBUG true [get_nets {u_cif/cpu_sels[2]}]
set_property MARK_DEBUG true [get_nets {u_cif/cpu_sels[3]}]
set_property MARK_DEBUG false [get_nets u_cif_n_80]
set_property MARK_DEBUG false [get_nets u_cif_n_81]
set_property MARK_DEBUG false [get_nets u_cif_n_82]
set_property MARK_DEBUG false [get_nets {p_leds_OBUF[2]}]

set_property MARK_DEBUG false [get_nets p_dc2_cs_n_OBUF]

set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[8]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[16]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[27]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[28]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[9]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[10]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[5]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[13]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[14]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[15]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[29]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[2]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[3]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[7]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[10]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[4]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[16]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[8]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[20]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[23]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[30]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[30]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[6]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[9]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[11]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[21]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[24]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[4]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[12]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[17]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[31]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[2]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[5]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[9]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[26]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[31]}]
set_property MARK_DEBUG true [get_nets cif_cpu_rdata_dv]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[20]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[22]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[11]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[1]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[7]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[0]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[25]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[0]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[13]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[18]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[26]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[6]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[3]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[8]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[7]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[10]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[6]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[21]}]
set_property MARK_DEBUG true [get_nets ps_cpu_wr]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[1]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[4]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[29]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[11]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[15]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[0]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[3]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[16]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[19]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[22]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[17]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[12]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[15]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[19]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_addr[2]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[12]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[14]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[18]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[27]}]
set_property MARK_DEBUG true [get_nets ps_cpu_rd]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[5]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[14]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[17]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[23]}]
set_property MARK_DEBUG true [get_nets {cif_cpu_rdata[25]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[1]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[13]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[24]}]
set_property MARK_DEBUG true [get_nets {ps_cpu_wdata[28]}]

