set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][9]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[1]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[2]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[3]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][7]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][8]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][11]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][13]}]
set_property MARK_DEBUG true [get_nets fifo_axis1_tvalid]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[5]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[14]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[11]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[13]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][12]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][0]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][2]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][3]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[8]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][14]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[6]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[7]}]
set_property MARK_DEBUG true [get_nets fifo_axis1_tlast]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[4]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[15]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[9]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][5]}]
set_property MARK_DEBUG true [get_nets fifo_axis1_tready]
set_property MARK_DEBUG true [get_nets fifo_almost_empty1]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][4]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][6]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][10]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[1][15]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[12]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[0]}]
set_property MARK_DEBUG true [get_nets {fifo_axis1_tdata[10]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][14]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][2]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][4]}]
set_property MARK_DEBUG true [get_nets fifo_axis0_tready]
set_property MARK_DEBUG true [get_nets fifo_almost_empty0]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[4]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[7]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[9]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[11]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[12]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[13]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[10]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][3]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][7]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[1]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[2]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[6]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][6]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][0]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][10]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][11]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][15]}]
set_property MARK_DEBUG true [get_nets resetn]
set_property MARK_DEBUG true [get_nets fifo_axis0_tlast]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[3]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[14]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][12]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][8]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[8]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][5]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][9]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tdatas[0][13]}]
set_property MARK_DEBUG true [get_nets clk]
set_property MARK_DEBUG true [get_nets fifo_axis0_tvalid]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[0]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[15]}]
set_property MARK_DEBUG true [get_nets {fifo_axis0_tdata[5]}]
set_property MARK_DEBUG true [get_nets pulse2pmod0_busy]
set_property MARK_DEBUG true [get_nets pulse2pmod1_busy]
set_property MARK_DEBUG true [get_nets p2p0_busy]
set_property MARK_DEBUG true [get_nets p2p1_busy]
set_property MARK_DEBUG true [get_nets dacs_pulse_busy]
set_property MARK_DEBUG true [get_nets ps_enable_dacs_pulse]
set_property MARK_DEBUG true [get_nets trigger_dacs_pulse]
set_property MARK_DEBUG false [get_nets {p_leds_OBUF[5]}]

set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[2]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[3]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[4]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[5]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[6]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[7]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[8]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[9]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[26]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[29]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[11]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[23]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[27]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[13]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[17]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[21]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[7]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[12]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[26]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[31]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[3]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[10]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[20]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[25]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[30]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[31]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[4]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[8]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[8]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[14]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[19]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[28]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[27]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[2]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[10]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[13]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[15]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[29]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[5]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[6]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[3]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[5]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[18]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[24]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[11]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[15]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[9]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[19]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[21]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[30]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[2]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[9]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[16]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[22]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[6]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[16]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[17]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[20]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[25]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[7]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[12]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[24]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[14]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[22]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tvalids[28]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[4]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[18]}]
set_property MARK_DEBUG false [get_nets {dacs_pulse_axis_tlasts[23]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tvalids[1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tvalids[0]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_treadys[0]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_treadys[1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tlasts[1]}]
set_property MARK_DEBUG true [get_nets {dacs_pulse_axis_tlasts[0]}]
connect_debug_port u_ila_0/probe23 [get_nets [list {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc}]]

set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[9]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[0]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[6]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[10]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[15]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[20]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[21]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[23]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[31]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[12]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[4]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[5]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[7]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[16]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[17]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[22]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[26]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[29]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[24]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[1]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[2]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[3]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[13]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[18]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[19]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[27]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[28]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[8]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[11]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[14]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[25]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[30]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_36}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_37}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_42}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_47}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_33}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_34}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_38}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_43}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_35}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_39}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_41}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_45}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_46}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_32}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_40}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/u_ram_waveform_n_44}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[2]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[3]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[11]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[12]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[15]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[20]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[27]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[31]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[4]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[5]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[7]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[10]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[13]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[14]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[19]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[25]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[29]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[0]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[8]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[9]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[18]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[21]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[22]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[23]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[26]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[1]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[6]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[16]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[17]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[24]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[28]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[30]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_32}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_33}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_36}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_44}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_35}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_37}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_38}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_39}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_40}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_41}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_45}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_46}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_47}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_34}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_42}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/u_ram_waveform_n_43}]

set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[10]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[12]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[13]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[15]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[18]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[8]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[9]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[11]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[14]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[16]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[17]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/A[19]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[4]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[6]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[7]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[9]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[0]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[1]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[2]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[3]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[5]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[8]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[8]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[11]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[12]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[13]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[14]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[16]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[18]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[19]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[9]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[10]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[15]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/A[17]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[2]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[3]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[4]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[0]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[1]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[5]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[6]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[7]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[8]}]
set_property MARK_DEBUG false [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_addrb_reg_n_0_[9]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[2]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[3]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[4]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[5]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[6]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[7]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[8]}]
set_property MARK_DEBUG true [get_nets {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[9]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_ps2/ps1_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dacs_pulse_axis_tdatas[0][0]} {dacs_pulse_axis_tdatas[0][1]} {dacs_pulse_axis_tdatas[0][2]} {dacs_pulse_axis_tdatas[0][3]} {dacs_pulse_axis_tdatas[0][4]} {dacs_pulse_axis_tdatas[0][5]} {dacs_pulse_axis_tdatas[0][6]} {dacs_pulse_axis_tdatas[0][7]} {dacs_pulse_axis_tdatas[0][8]} {dacs_pulse_axis_tdatas[0][9]} {dacs_pulse_axis_tdatas[0][10]} {dacs_pulse_axis_tdatas[0][11]} {dacs_pulse_axis_tdatas[0][12]} {dacs_pulse_axis_tdatas[0][13]} {dacs_pulse_axis_tdatas[0][14]} {dacs_pulse_axis_tdatas[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {dacs_pulse_axis_tdatas[1][0]} {dacs_pulse_axis_tdatas[1][1]} {dacs_pulse_axis_tdatas[1][2]} {dacs_pulse_axis_tdatas[1][3]} {dacs_pulse_axis_tdatas[1][4]} {dacs_pulse_axis_tdatas[1][5]} {dacs_pulse_axis_tdatas[1][6]} {dacs_pulse_axis_tdatas[1][7]} {dacs_pulse_axis_tdatas[1][8]} {dacs_pulse_axis_tdatas[1][9]} {dacs_pulse_axis_tdatas[1][10]} {dacs_pulse_axis_tdatas[1][11]} {dacs_pulse_axis_tdatas[1][12]} {dacs_pulse_axis_tdatas[1][13]} {dacs_pulse_axis_tdatas[1][14]} {dacs_pulse_axis_tdatas[1][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {dacs_pulse_axis_tlasts[0]} {dacs_pulse_axis_tlasts[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {fifo_axis1_tdata[0]} {fifo_axis1_tdata[1]} {fifo_axis1_tdata[2]} {fifo_axis1_tdata[3]} {fifo_axis1_tdata[4]} {fifo_axis1_tdata[5]} {fifo_axis1_tdata[6]} {fifo_axis1_tdata[7]} {fifo_axis1_tdata[8]} {fifo_axis1_tdata[9]} {fifo_axis1_tdata[10]} {fifo_axis1_tdata[11]} {fifo_axis1_tdata[12]} {fifo_axis1_tdata[13]} {fifo_axis1_tdata[14]} {fifo_axis1_tdata[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {fifo_axis0_tdata[0]} {fifo_axis0_tdata[1]} {fifo_axis0_tdata[2]} {fifo_axis0_tdata[3]} {fifo_axis0_tdata[4]} {fifo_axis0_tdata[5]} {fifo_axis0_tdata[6]} {fifo_axis0_tdata[7]} {fifo_axis0_tdata[8]} {fifo_axis0_tdata[9]} {fifo_axis0_tdata[10]} {fifo_axis0_tdata[11]} {fifo_axis0_tdata[12]} {fifo_axis0_tdata[13]} {fifo_axis0_tdata[14]} {fifo_axis0_tdata[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {dacs_pulse_axis_treadys[0]} {dacs_pulse_axis_treadys[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {dacs_pulse_axis_tvalids[0]} {dacs_pulse_axis_tvalids[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[2]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[3]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[4]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[5]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[6]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[7]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[8]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/pc[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[0]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[1]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[2]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[3]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[4]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[5]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[6]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_waveform_addrb__0[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[0]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[1]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[2]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[3]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[4]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[5]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[6]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[7]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[8]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[9]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[10]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[11]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[12]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[13]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[14]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[15]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[16]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[17]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[18]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[19]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[20]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[21]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[22]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[23]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[24]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[25]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[26]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[27]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[28]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[29]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[30]} {u_dacs_pulse/g_ch[1].ch_full.u_ch/ram_pulse_doutb[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 10 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[0]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[1]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[2]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[3]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[4]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[5]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[6]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[7]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[8]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/pc[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[0]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[1]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[2]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[3]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[4]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[5]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[6]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_waveform_addrb[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[0]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[1]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[2]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[3]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[4]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[5]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[6]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[7]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[8]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[9]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[10]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[11]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[12]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[13]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[14]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[15]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[16]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[17]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[18]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[19]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[20]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[21]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[22]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[23]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[24]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[25]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[26]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[27]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[28]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[29]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[30]} {u_dacs_pulse/g_ch[0].ch_full.u_ch/ram_pulse_doutb[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list dacs_pulse_busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list fifo_almost_empty0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list fifo_almost_empty1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list fifo_axis0_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list fifo_axis0_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list fifo_axis0_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list fifo_axis1_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list fifo_axis1_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list fifo_axis1_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list p2p0_busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list p2p1_busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list ps_enable_dacs_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list pulse2pmod0_busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list pulse2pmod1_busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list resetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list trigger_dacs_pulse]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
